# Generated by Django 5.0.2 on 2024-02-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название материала')),
                ('description', models.TextField(blank='True', null='True', verbose_name='описание материала')),
                ('image', models.ImageField(blank='True', null='True', upload_to='material/', verbose_name='картинка материала')),
                ('url', models.URLField(blank='True', null='True', verbose_name='ссылка на видео')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название раздела')),
                ('image', models.ImageField(blank='True', null='True', upload_to='section/', verbose_name='картинка раздела')),
                ('description', models.TextField(blank='True', null='True', verbose_name='описание раздела')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank='True', max_length=300, null='True', verbose_name='вопрос по материалу')),
                ('answer', models.CharField(blank='True', choices=[('Yes', 'Да'), ('No', 'Нет')], max_length=4, null='True', verbose_name='верный ответ')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
