# Generated by Django 5.0.2 on 2024-03-11 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='questions',
        ),
        migrations.AddField(
            model_name='test',
            name='materials',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='education.material', verbose_name='материал'),
            preserve_default='True',
        ),
    ]
