# Generated by Django 5.0.2 on 2024-03-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_remove_material_questions_test_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='tests',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='education.test'),
            preserve_default='True',
        ),
    ]
