# Generated by Django 5.0.2 on 2024-03-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_material_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='tests',
        ),
    ]
